# Copyright 2026 SOFTYONARY SL
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load(":celix_bundle_test.bzl", "celix_bundle_analysis_test_suite")
load(":celix_convenience_test.bzl", "celix_convenience_analysis_test_suite")
load(":celix_runtime_test.bzl", "celix_runtime_analysis_test_suite")
load(":manifest_test.bzl", "manifest_test_suite")

package(default_testonly = True)

celix_bundle_analysis_test_suite(
    name = "celix_bundle_test",
)

celix_convenience_analysis_test_suite(
    name = "celix_convenience_test",
)

celix_runtime_analysis_test_suite(
    name = "celix_runtime_test",
)

manifest_test_suite(
    name = "manifest_test",
)

test_suite(
    name = "all_tests",
    tests = [
        ":celix_bundle_test_filename",
        ":celix_bundle_test_missing_activator",
        ":celix_bundle_test_no_activator",
        ":celix_bundle_test_provider",
        ":celix_convenience_test_copts_linkopts",
        ":celix_convenience_test_includes",
        ":celix_convenience_test_missing_srcs",
        ":celix_convenience_test_provider_c",
        ":celix_convenience_test_provider_cpp",
        ":celix_runtime_test_provider",
        ":manifest_test",
        "//tests/integration:validate_bundle_default_name_test",
        "//tests/integration:validate_bundle_full_test",
        "//tests/integration:validate_bundle_no_activator_test",
        "//tests/integration:validate_bundle_test",
        "//tests/integration:validate_bundle_v3_json_test",
        "//tests/integration:validate_macro_c_bundle_test",
        "//tests/integration:validate_macro_cpp_bundle_test",
        "//tests/integration:validate_macro_flags_bundle_test",
    ],
)
